# Generated by Django 5.1.2 on 2024-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('hours', models.PositiveIntegerField()),
                ('lecturer', models.CharField(max_length=100)),
            ],
        ),
    ]
